.TH man 7 sheriff-buzz

.SH NAME
sheriff-buzz \- intrusion detection and response with eBPF

.SH SYNOPSIS
sheriff-buzz -i <interface> | -a <address> [OPTIONS]

.SH DESCRIPTION
Detect port scans, blocking/redirecting traffic from hosts deemed suspicious.

A network interface name or address to attach to is required, all other
arguments are optional.

.SH OPTIONS

.TP
.B --interface, -i <name>
name of network interface to attach to

.TP
.B --address, -a <address>
address of network interface to attach to

.TP
.B --config, -c <path>
path to JSON config file (default is
.B ./config/default.json)

.TP
.B --log, -l <path>
path to log file (default is 
.B /var/log/sheriff-buzz.log)

.TP
.B --bpf-obj, -b <path>
path to BPF object file (default is 
.B ./src/sheriff-buzz.bpf.o)

.TP
.B --skb-mode, -s
enable SKB mode (use if native XDP not supported)

.TP
.B --dry-run, -d
enable dry run mode (do not block/redirect traffic from blacklisted IPs/subnets)

.TP
.B --test, -t
enable testing mode (additional logging and storage of packets from test subnet)

.SH AUTHOR
Salma Berriche (smb114@student.bham.ac.uk)

.SH COPYRIGHT
License GPLv2+: GNU GPL version 2 or later: <https://spdx.org/licenses/GPL-2.0.html>
